parameters:
  app.secret: "CHANGE_ME_IN_INSTALLER"
  database.url: "mysql://app:password@127.0.0.1:3306/app?serverVersion=8.0&charset=utf8mb4"
  mikrotik.matrix_url: "https://mikrotik.com/products"
  mikrotik.matrix_referer: "https://mikrotik.com/products/matrix"
