imports:
  - { resource: parameters.yaml }
  - { resource: parameters.local.yaml, ignore_errors: true }

parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true 

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]