name: tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2, phpunit
          extensions: intl, pdo_sqlite
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Prepare test cache dirs
        run: |
          mkdir -p var/.phpunit-cache var/cache/test var/log

      - name: Run PHPUnit
        env:
          APP_ENV: test
          APP_DEBUG: 1
        run: vendor/bin/phpunit -c phpunit.xml.dist --testdox

      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist --no-progress


